-- 050__drop.sql
DROP TABLE IF EXISTS options    CASCADE;
-- DROP TABLE IF EXISTS answers    CASCADE;
-- DROP TABLE IF EXISTS attempts   CASCADE;
-- DROP TABLE IF EXISTS ratings    CASCADE;
-- DROP TABLE IF EXISTS messages   CASCADE;
-- DROP TABLE IF EXISTS follows    CASCADE;
DROP TABLE IF EXISTS questions  CASCADE;
DROP TABLE IF EXISTS quizzes    CASCADE;
DROP TABLE IF EXISTS users      CASCADE;
DROP TABLE IF EXISTS _migrations CASCADE;